name: replicate-segfault
on:
  push:
  workflow_dispatch:

jobs:
  cause_segfault:
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
      - name: Install and run segfaulting code
        shell: bash -l {0}
        run: |
          python -m pip install numpy
          python -m pip install -vvv .
          python cause_segfault.py -n 101 --order 24 # Doesn't segfault
          python cause_segfault.py -n 100 --order 24 # Does segfault
